"""
MSM Celestial Egg Zapping Requirements
Extracted from My Singing Monsters wiki and MSMPokeGamer.
Format: List of (monster_name, egg_name, quantity) tuples.
"""

CELESTIAL_EGG_REQUIREMENTS = [
    # Galvana (Lightning Element) - from MSMPokeGamer
    ("Galvana", "Noggin", 10),
    ("Galvana", "Drumpler", 5),
    ("Galvana", "Dandidoo", 4),
    ("Galvana", "Glowl", 3),
    ("Galvana", "Thumpies", 3),
    ("Galvana", "Floogull", 2),
    ("Galvana", "Quarrister", 1),
    ("Galvana", "Mammott", 10),
    ("Galvana", "Fwog", 5),
    ("Galvana", "Pango", 4),
    ("Galvana", "T-Rox", 3),
    ("Galvana", "Congle", 3),
    ("Galvana", "Barrb", 2),
    ("Galvana", "Tring", 1),
    ("Galvana", "Toe Jammer", 10),
    ("Galvana", "Maw", 5),
    ("Galvana", "Quibble", 4),
    ("Galvana", "Pummel", 3),
    ("Galvana", "PomPom", 3),
    ("Galvana", "Entbrat", 1),
    ("Galvana", "Potbelly", 10),
    ("Galvana", "Shrubb", 4),
    ("Galvana", "Cybop", 4),
    ("Galvana", "Clamble", 3),
    ("Galvana", "Scups", 3),
    ("Galvana", "Deedge", 1),
    ("Galvana", "Tweedle", 10),
    ("Galvana", "Furcorn", 4),
    ("Galvana", "Stogg", 3),
    ("Galvana", "Bowgart", 3),
    ("Galvana", "Reedling", 3),
    ("Galvana", "Riff", 1),
    ("Galvana", "Kayna", 6),
    ("Galvana", "Oaktopus", 4),
    ("Galvana", "Flowah", 3),
    ("Galvana", "Spunge", 3),
    ("Galvana", "Repatillo", 2),
    ("Galvana", "Shellbeat", 1),
    # Glaishur (Cold Element)
    ("Glaishur", "Mammott", 40),
    ("Glaishur", "T-Rox", 2),
    ("Glaishur", "Drumpler", 7),
    ("Glaishur", "Thumpies", 2),
    ("Glaishur", "Maw", 5),
    ("Glaishur", "Congle", 2),
    ("Glaishur", "Furcorn", 10),
    ("Glaishur", "Bowgart", 3),
    ("Glaishur", "Pango", 8),
    ("Glaishur", "PomPom", 3),
    ("Glaishur", "Clamble", 1),
    ("Glaishur", "Deedge", 4),
    # Hornacle (Water Element)
    ("Hornacle", "Toe Jammer", 50),
    ("Hornacle", "Pummel", 5),
    ("Hornacle", "Fwog", 15),
    ("Hornacle", "Bowgart", 4),
    ("Hornacle", "Maw", 9),
    ("Hornacle", "Scups", 4),
    ("Hornacle", "Oaktopus", 12),
    ("Hornacle", "Spunge", 3),
    ("Hornacle", "Quibble", 8),
    ("Hornacle", "Congle", 3),
    ("Hornacle", "T-Rox", 2),
    ("Hornacle", "Shellbeat", 3),
    # Torrt (Earth Element)
    ("Torrt", "Noggin", 50),
    ("Torrt", "Scups", 1),
    ("Torrt", "Drumpler", 6),
    ("Torrt", "Pummel", 2),
    ("Torrt", "Fwog", 4),
    ("Torrt", "Reedling", 2),
    ("Torrt", "Shrubb", 4),
    ("Torrt", "Clamble", 2),
    ("Torrt", "Cybop", 6),
    ("Torrt", "PomPom", 3),
    ("Torrt", "T-Rox", 6),
    ("Torrt", "Quarrister", 1),
    # Attmoz (Air Element)
    ("Attmoz", "Tweedle", 25),
    ("Attmoz", "Thumpies", 2),
    ("Attmoz", "Dandidoo", 5),
    ("Attmoz", "Congle", 2),
    ("Attmoz", "Pango", 6),
    ("Attmoz", "Scups", 2),
    ("Attmoz", "Quibble", 6),
    ("Attmoz", "PomPom", 3),
    ("Attmoz", "Cybop", 8),
    ("Attmoz", "Reedling", 1),
    ("Attmoz", "Spunge", 2),
    ("Attmoz", "Riff", 3),
    # Blasoom (Plant Element)
    ("Blasoom", "Potbelly", 20),
    ("Blasoom", "Thumpies", 4),
    ("Blasoom", "Shrubb", 5),
    ("Blasoom", "Reedling", 4),
    ("Blasoom", "Oaktopus", 5),
    ("Blasoom", "Spunge", 3),
    ("Blasoom", "Dandidoo", 8),
    ("Blasoom", "Pummel", 3),
    ("Blasoom", "Furcorn", 9),
    ("Blasoom", "Bowgart", 3),
    ("Blasoom", "Clamble", 5),
    ("Blasoom", "Entbrat", 3),
    # Syncopite (Crystal Element)
    ("Syncopite", "Noggin", 75),
    ("Syncopite", "Cybop", 3),
    ("Syncopite", "Reedling", 4),
    ("Syncopite", "Toe Jammer", 30),
    ("Syncopite", "Oaktopus", 5),
    ("Syncopite", "Spunge", 6),
    ("Syncopite", "Potbelly", 12),
    ("Syncopite", "Dandidoo", 6),
    ("Syncopite", "Shellbeat", 2),
    ("Syncopite", "Tweedle", 6),
    ("Syncopite", "Quibble", 6),
    ("Syncopite", "Fwog", 10),
    ("Syncopite", "Scups", 3),
    ("Syncopite", "Shrubb", 2),
    ("Syncopite", "Pummel", 4),
    # Vhamp (Mech Element)
    ("Vhamp", "Noggin", 50),
    ("Vhamp", "Drumpler", 12),
    ("Vhamp", "Scups", 3),
    ("Vhamp", "Toe Jammer", 50),
    ("Vhamp", "Quibble", 5),
    ("Vhamp", "PomPom", 1),
    ("Vhamp", "Mammott", 35),
    ("Vhamp", "Pango", 5),
    ("Vhamp", "Riff", 1),
    ("Vhamp", "Tweedle", 9),
    ("Vhamp", "Cybop", 15),
    ("Vhamp", "Fwog", 5),
    ("Vhamp", "T-Rox", 4),
    ("Vhamp", "Maw", 7),
    ("Vhamp", "Congle", 3),
    # Scaratar (Poison Element)
    ("Scaratar", "Noggin", 36),
    ("Scaratar", "Shrubb", 6),
    ("Scaratar", "Clamble", 3),
    ("Scaratar", "Mammott", 25),
    ("Scaratar", "Dandidoo", 5),
    ("Scaratar", "Thumpies", 4),
    ("Scaratar", "Potbelly", 16),
    ("Scaratar", "Pango", 3),
    ("Scaratar", "Quarrister", 2),
    ("Scaratar", "Tweedle", 6),
    ("Scaratar", "Cybop", 3),
    ("Scaratar", "Drumpler", 4),
    ("Scaratar", "PomPom", 1),
    ("Scaratar", "Furcorn", 7),
    ("Scaratar", "Reedling", 2),
    # Loodvigg (Shadow Element)
    ("Loodvigg", "Toe Jammer", 30),
    ("Loodvigg", "Quibble", 4),
    ("Loodvigg", "Congle", 2),
    ("Loodvigg", "Potbelly", 6),
    ("Loodvigg", "Dandidoo", 5),
    ("Loodvigg", "Bowgart", 5),
    ("Loodvigg", "Mammott", 25),
    ("Loodvigg", "Furcorn", 6),
    ("Loodvigg", "Deedge", 2),
    ("Loodvigg", "Tweedle", 8),
    ("Loodvigg", "Oaktopus", 8),
    ("Loodvigg", "Maw", 15),
    ("Loodvigg", "Spunge", 1),
    ("Loodvigg", "Pango", 2),
    ("Loodvigg", "Thumpies", 2),
    # Furnoss (Fire Element)
    ("Furnoss", "Noggin", 25),
    ("Furnoss", "Cybop", 2),
    ("Furnoss", "Repatillo", 3),
    ("Furnoss", "Potbelly", 10),
    ("Furnoss", "Glowl", 7),
    ("Furnoss", "Barrb", 3),
    ("Furnoss", "Tweedle", 5),
    ("Furnoss", "Stogg", 5),
    ("Furnoss", "Tring", 2),
    ("Furnoss", "Kayna", 15),
    ("Furnoss", "Flowah", 5),
    ("Furnoss", "Shrubb", 3),
    ("Furnoss", "Floogull", 4),
    ("Furnoss", "Dandidoo", 2),
    ("Furnoss", "Reedling", 3),
    # Plixie (Plasma Element)
    ("Plixie", "Noggin", 70),
    ("Plixie", "Maw", 35),
    ("Plixie", "Pummel", 2),
    ("Plixie", "Toe Jammer", 25),
    ("Plixie", "Furcorn", 7),
    ("Plixie", "Clamble", 2),
    ("Plixie", "Mammott", 25),
    ("Plixie", "Shrubb", 8),
    ("Plixie", "Entbrat", 5),
    ("Plixie", "Potbelly", 16),
    ("Plixie", "Oaktopus", 15),
    ("Plixie", "Drumpler", 12),
    ("Plixie", "T-Rox", 4),
    ("Plixie", "Fwog", 20),
    ("Plixie", "Bowgart", 3),
]


def get_requirements_by_monster(monster_name: str) -> list[tuple[str, int]]:
    """Return list of (egg_name, quantity) for a given Celestial."""
    return [
        (egg, qty)
        for mon, egg, qty in CELESTIAL_EGG_REQUIREMENTS
        if mon == monster_name
    ]


def get_all_monsters() -> list[str]:
    """Return list of all Celestial monster names."""
    return list(dict.fromkeys(m for m, _, _ in CELESTIAL_EGG_REQUIREMENTS))


if __name__ == "__main__":
    for monster in get_all_monsters():
        eggs = get_requirements_by_monster(monster)
        total = sum(q for _, q in eggs)
        print(f"{monster}: {len(eggs)} egg types, {total} total eggs")
